name: New CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: поздороваться
      run: echo Hello, world!

    - name: проверить код на pep8
      run: |
        pip3 install flake8
        python3 -m flake8 hello.py
        
    - name: проверить код на pep8
      run: |
        pip3 install pytest
        python3 -m pytest

    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASS }}
        port: ${{ secrets.PORT }}
        connect_timeout: 10s
        script: |
          ls -la  
          echo $WELCOME 
          mkdir tst
