name: New CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: поздороваться
      run: echo Hello, world!

    - name: проверить код на pep8
      run: |
        pip3 install flake8
        flake8 hello.py
        
    - name: проверить код на pep8
      run: |
        pip3 install pytest
        pytest
