name: New CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH remote command executer
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: touch privet1
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASS }}