name: New CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: поздороваться
      run: echo Hello, world!

    - name: проверить код на pep8
      run: |
        pip install flake8
        flake8 .
        
    - name: проверить код на pep8
      run: |
        pip install pytest
        pytest
